# Makefile for downloading project specifications
# from the internet.
#
# Links found at:
# * http://www.nyxdata.com/nysedata/Default.aspx?tabid=1084


download:
	wget -O xdp-integrated-feed-client-specification.pdf http://www.nyxdata.com/doc/77186
	wget -O nyse-arca-integrated-feed-sample-data-directory-layout.pdf http://www.nyxdata.com/doc/76675
