# Makefile for downloading project specifications
# from the internet.
#
# Links found at:
# * http://www.nyxdata.com/nysedata/Default.aspx?tabid=1084


download:
	wget -O "XDP Integrated Feed Client Spec v1.7.pdf" http://www.nyxdata.com/doc/77186
	wget -O "XDP Common Client Spec v1.0.pdf" http://www.nyxdata.com/doc/69004
	wget -O "NYSE Arca Integrated Feed Sample Data Directory Layout.pdf" http://www.nyxdata.com/doc/76675
