// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: visProt.proto

package oxberryPis;

public final class VisProt {
  private VisProt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StockEventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 stock_id = 1;
    /**
     * <code>required int32 stock_id = 1;</code>
     */
    boolean hasStockId();
    /**
     * <code>required int32 stock_id = 1;</code>
     */
    int getStockId();

    // required int32 timestamp = 2;
    /**
     * <code>required int32 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int32 timestamp = 2;</code>
     */
    int getTimestamp();

    // required int32 pi_id = 3;
    /**
     * <code>required int32 pi_id = 3;</code>
     */
    boolean hasPiId();
    /**
     * <code>required int32 pi_id = 3;</code>
     */
    int getPiId();

    // optional int32 top_buy_price = 4;
    /**
     * <code>optional int32 top_buy_price = 4;</code>
     */
    boolean hasTopBuyPrice();
    /**
     * <code>optional int32 top_buy_price = 4;</code>
     */
    int getTopBuyPrice();

    // optional int32 top_sell_price = 5;
    /**
     * <code>optional int32 top_sell_price = 5;</code>
     */
    boolean hasTopSellPrice();
    /**
     * <code>optional int32 top_sell_price = 5;</code>
     */
    int getTopSellPrice();

    // optional int32 trade_price = 6;
    /**
     * <code>optional int32 trade_price = 6;</code>
     */
    boolean hasTradePrice();
    /**
     * <code>optional int32 trade_price = 6;</code>
     */
    int getTradePrice();

    // required int32 seq_number = 7;
    /**
     * <code>required int32 seq_number = 7;</code>
     */
    boolean hasSeqNumber();
    /**
     * <code>required int32 seq_number = 7;</code>
     */
    int getSeqNumber();
  }
  /**
   * Protobuf type {@code oxberryPis.StockEvent}
   *
   * <pre>
   * somthing changed to be sent to visualisation
   * </pre>
   */
  public static final class StockEvent extends
      com.google.protobuf.GeneratedMessage
      implements StockEventOrBuilder {
    // Use StockEvent.newBuilder() to construct.
    private StockEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StockEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StockEvent defaultInstance;
    public static StockEvent getDefaultInstance() {
      return defaultInstance;
    }

    public StockEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StockEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stockId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              piId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              topBuyPrice_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              topSellPrice_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              tradePrice_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              seqNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return oxberryPis.VisProt.internal_static_oxberryPis_StockEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return oxberryPis.VisProt.internal_static_oxberryPis_StockEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              oxberryPis.VisProt.StockEvent.class, oxberryPis.VisProt.StockEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<StockEvent> PARSER =
        new com.google.protobuf.AbstractParser<StockEvent>() {
      public StockEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StockEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 stock_id = 1;
    public static final int STOCK_ID_FIELD_NUMBER = 1;
    private int stockId_;
    /**
     * <code>required int32 stock_id = 1;</code>
     */
    public boolean hasStockId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 stock_id = 1;</code>
     */
    public int getStockId() {
      return stockId_;
    }

    // required int32 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private int timestamp_;
    /**
     * <code>required int32 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 timestamp = 2;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    // required int32 pi_id = 3;
    public static final int PI_ID_FIELD_NUMBER = 3;
    private int piId_;
    /**
     * <code>required int32 pi_id = 3;</code>
     */
    public boolean hasPiId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pi_id = 3;</code>
     */
    public int getPiId() {
      return piId_;
    }

    // optional int32 top_buy_price = 4;
    public static final int TOP_BUY_PRICE_FIELD_NUMBER = 4;
    private int topBuyPrice_;
    /**
     * <code>optional int32 top_buy_price = 4;</code>
     */
    public boolean hasTopBuyPrice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 top_buy_price = 4;</code>
     */
    public int getTopBuyPrice() {
      return topBuyPrice_;
    }

    // optional int32 top_sell_price = 5;
    public static final int TOP_SELL_PRICE_FIELD_NUMBER = 5;
    private int topSellPrice_;
    /**
     * <code>optional int32 top_sell_price = 5;</code>
     */
    public boolean hasTopSellPrice() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 top_sell_price = 5;</code>
     */
    public int getTopSellPrice() {
      return topSellPrice_;
    }

    // optional int32 trade_price = 6;
    public static final int TRADE_PRICE_FIELD_NUMBER = 6;
    private int tradePrice_;
    /**
     * <code>optional int32 trade_price = 6;</code>
     */
    public boolean hasTradePrice() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 trade_price = 6;</code>
     */
    public int getTradePrice() {
      return tradePrice_;
    }

    // required int32 seq_number = 7;
    public static final int SEQ_NUMBER_FIELD_NUMBER = 7;
    private int seqNumber_;
    /**
     * <code>required int32 seq_number = 7;</code>
     */
    public boolean hasSeqNumber() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 seq_number = 7;</code>
     */
    public int getSeqNumber() {
      return seqNumber_;
    }

    private void initFields() {
      stockId_ = 0;
      timestamp_ = 0;
      piId_ = 0;
      topBuyPrice_ = 0;
      topSellPrice_ = 0;
      tradePrice_ = 0;
      seqNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStockId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPiId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeqNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, stockId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, piId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, topBuyPrice_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, topSellPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, tradePrice_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, seqNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, stockId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, piId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, topBuyPrice_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, topSellPrice_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, tradePrice_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, seqNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static oxberryPis.VisProt.StockEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oxberryPis.VisProt.StockEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oxberryPis.VisProt.StockEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oxberryPis.VisProt.StockEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oxberryPis.VisProt.StockEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static oxberryPis.VisProt.StockEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static oxberryPis.VisProt.StockEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static oxberryPis.VisProt.StockEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static oxberryPis.VisProt.StockEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static oxberryPis.VisProt.StockEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(oxberryPis.VisProt.StockEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oxberryPis.StockEvent}
     *
     * <pre>
     * somthing changed to be sent to visualisation
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements oxberryPis.VisProt.StockEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return oxberryPis.VisProt.internal_static_oxberryPis_StockEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return oxberryPis.VisProt.internal_static_oxberryPis_StockEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                oxberryPis.VisProt.StockEvent.class, oxberryPis.VisProt.StockEvent.Builder.class);
      }

      // Construct using oxberryPis.VisProt.StockEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stockId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        piId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        topBuyPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        topSellPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        tradePrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        seqNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return oxberryPis.VisProt.internal_static_oxberryPis_StockEvent_descriptor;
      }

      public oxberryPis.VisProt.StockEvent getDefaultInstanceForType() {
        return oxberryPis.VisProt.StockEvent.getDefaultInstance();
      }

      public oxberryPis.VisProt.StockEvent build() {
        oxberryPis.VisProt.StockEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public oxberryPis.VisProt.StockEvent buildPartial() {
        oxberryPis.VisProt.StockEvent result = new oxberryPis.VisProt.StockEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stockId_ = stockId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.piId_ = piId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.topBuyPrice_ = topBuyPrice_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.topSellPrice_ = topSellPrice_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tradePrice_ = tradePrice_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.seqNumber_ = seqNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof oxberryPis.VisProt.StockEvent) {
          return mergeFrom((oxberryPis.VisProt.StockEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(oxberryPis.VisProt.StockEvent other) {
        if (other == oxberryPis.VisProt.StockEvent.getDefaultInstance()) return this;
        if (other.hasStockId()) {
          setStockId(other.getStockId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasPiId()) {
          setPiId(other.getPiId());
        }
        if (other.hasTopBuyPrice()) {
          setTopBuyPrice(other.getTopBuyPrice());
        }
        if (other.hasTopSellPrice()) {
          setTopSellPrice(other.getTopSellPrice());
        }
        if (other.hasTradePrice()) {
          setTradePrice(other.getTradePrice());
        }
        if (other.hasSeqNumber()) {
          setSeqNumber(other.getSeqNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStockId()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasPiId()) {
          
          return false;
        }
        if (!hasSeqNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        oxberryPis.VisProt.StockEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (oxberryPis.VisProt.StockEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 stock_id = 1;
      private int stockId_ ;
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      public boolean hasStockId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      public int getStockId() {
        return stockId_;
      }
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      public Builder setStockId(int value) {
        bitField0_ |= 0x00000001;
        stockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      public Builder clearStockId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stockId_ = 0;
        onChanged();
        return this;
      }

      // required int32 timestamp = 2;
      private int timestamp_ ;
      /**
       * <code>required int32 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 timestamp = 2;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int32 timestamp = 2;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      // required int32 pi_id = 3;
      private int piId_ ;
      /**
       * <code>required int32 pi_id = 3;</code>
       */
      public boolean hasPiId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pi_id = 3;</code>
       */
      public int getPiId() {
        return piId_;
      }
      /**
       * <code>required int32 pi_id = 3;</code>
       */
      public Builder setPiId(int value) {
        bitField0_ |= 0x00000004;
        piId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pi_id = 3;</code>
       */
      public Builder clearPiId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        piId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 top_buy_price = 4;
      private int topBuyPrice_ ;
      /**
       * <code>optional int32 top_buy_price = 4;</code>
       */
      public boolean hasTopBuyPrice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 top_buy_price = 4;</code>
       */
      public int getTopBuyPrice() {
        return topBuyPrice_;
      }
      /**
       * <code>optional int32 top_buy_price = 4;</code>
       */
      public Builder setTopBuyPrice(int value) {
        bitField0_ |= 0x00000008;
        topBuyPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 top_buy_price = 4;</code>
       */
      public Builder clearTopBuyPrice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        topBuyPrice_ = 0;
        onChanged();
        return this;
      }

      // optional int32 top_sell_price = 5;
      private int topSellPrice_ ;
      /**
       * <code>optional int32 top_sell_price = 5;</code>
       */
      public boolean hasTopSellPrice() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 top_sell_price = 5;</code>
       */
      public int getTopSellPrice() {
        return topSellPrice_;
      }
      /**
       * <code>optional int32 top_sell_price = 5;</code>
       */
      public Builder setTopSellPrice(int value) {
        bitField0_ |= 0x00000010;
        topSellPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 top_sell_price = 5;</code>
       */
      public Builder clearTopSellPrice() {
        bitField0_ = (bitField0_ & ~0x00000010);
        topSellPrice_ = 0;
        onChanged();
        return this;
      }

      // optional int32 trade_price = 6;
      private int tradePrice_ ;
      /**
       * <code>optional int32 trade_price = 6;</code>
       */
      public boolean hasTradePrice() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 trade_price = 6;</code>
       */
      public int getTradePrice() {
        return tradePrice_;
      }
      /**
       * <code>optional int32 trade_price = 6;</code>
       */
      public Builder setTradePrice(int value) {
        bitField0_ |= 0x00000020;
        tradePrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 trade_price = 6;</code>
       */
      public Builder clearTradePrice() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tradePrice_ = 0;
        onChanged();
        return this;
      }

      // required int32 seq_number = 7;
      private int seqNumber_ ;
      /**
       * <code>required int32 seq_number = 7;</code>
       */
      public boolean hasSeqNumber() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 seq_number = 7;</code>
       */
      public int getSeqNumber() {
        return seqNumber_;
      }
      /**
       * <code>required int32 seq_number = 7;</code>
       */
      public Builder setSeqNumber(int value) {
        bitField0_ |= 0x00000040;
        seqNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seq_number = 7;</code>
       */
      public Builder clearSeqNumber() {
        bitField0_ = (bitField0_ & ~0x00000040);
        seqNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:oxberryPis.StockEvent)
    }

    static {
      defaultInstance = new StockEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:oxberryPis.StockEvent)
  }

  public interface SetupVisualisationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 denomPower = 1;
    /**
     * <code>required int32 denomPower = 1;</code>
     */
    boolean hasDenomPower();
    /**
     * <code>required int32 denomPower = 1;</code>
     */
    int getDenomPower();

    // repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    java.util.List<oxberryPis.VisProt.SetupVisualisation.StockDefn> 
        getStocksList();
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    oxberryPis.VisProt.SetupVisualisation.StockDefn getStocks(int index);
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    int getStocksCount();
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    java.util.List<? extends oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder> 
        getStocksOrBuilderList();
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder getStocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code oxberryPis.SetupVisualisation}
   */
  public static final class SetupVisualisation extends
      com.google.protobuf.GeneratedMessage
      implements SetupVisualisationOrBuilder {
    // Use SetupVisualisation.newBuilder() to construct.
    private SetupVisualisation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SetupVisualisation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SetupVisualisation defaultInstance;
    public static SetupVisualisation getDefaultInstance() {
      return defaultInstance;
    }

    public SetupVisualisation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SetupVisualisation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              denomPower_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                stocks_ = new java.util.ArrayList<oxberryPis.VisProt.SetupVisualisation.StockDefn>();
                mutable_bitField0_ |= 0x00000002;
              }
              stocks_.add(input.readMessage(oxberryPis.VisProt.SetupVisualisation.StockDefn.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          stocks_ = java.util.Collections.unmodifiableList(stocks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              oxberryPis.VisProt.SetupVisualisation.class, oxberryPis.VisProt.SetupVisualisation.Builder.class);
    }

    public static com.google.protobuf.Parser<SetupVisualisation> PARSER =
        new com.google.protobuf.AbstractParser<SetupVisualisation>() {
      public SetupVisualisation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetupVisualisation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SetupVisualisation> getParserForType() {
      return PARSER;
    }

    public interface StockDefnOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 stock_id = 1;
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      boolean hasStockId();
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      int getStockId();

      // required string stock_name = 2;
      /**
       * <code>required string stock_name = 2;</code>
       */
      boolean hasStockName();
      /**
       * <code>required string stock_name = 2;</code>
       */
      java.lang.String getStockName();
      /**
       * <code>required string stock_name = 2;</code>
       */
      com.google.protobuf.ByteString
          getStockNameBytes();

      // required int32 stream_id = 3;
      /**
       * <code>required int32 stream_id = 3;</code>
       */
      boolean hasStreamId();
      /**
       * <code>required int32 stream_id = 3;</code>
       */
      int getStreamId();

      // repeated int32 pi_ids = 4;
      /**
       * <code>repeated int32 pi_ids = 4;</code>
       */
      java.util.List<java.lang.Integer> getPiIdsList();
      /**
       * <code>repeated int32 pi_ids = 4;</code>
       */
      int getPiIdsCount();
      /**
       * <code>repeated int32 pi_ids = 4;</code>
       */
      int getPiIds(int index);
    }
    /**
     * Protobuf type {@code oxberryPis.SetupVisualisation.StockDefn}
     */
    public static final class StockDefn extends
        com.google.protobuf.GeneratedMessage
        implements StockDefnOrBuilder {
      // Use StockDefn.newBuilder() to construct.
      private StockDefn(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private StockDefn(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final StockDefn defaultInstance;
      public static StockDefn getDefaultInstance() {
        return defaultInstance;
      }

      public StockDefn getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private StockDefn(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                stockId_ = input.readInt32();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                stockName_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                streamId_ = input.readInt32();
                break;
              }
              case 32: {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  piIds_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000008;
                }
                piIds_.add(input.readInt32());
                break;
              }
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                  piIds_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000008;
                }
                while (input.getBytesUntilLimit() > 0) {
                  piIds_.add(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
            piIds_ = java.util.Collections.unmodifiableList(piIds_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_StockDefn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_StockDefn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                oxberryPis.VisProt.SetupVisualisation.StockDefn.class, oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder.class);
      }

      public static com.google.protobuf.Parser<StockDefn> PARSER =
          new com.google.protobuf.AbstractParser<StockDefn>() {
        public StockDefn parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new StockDefn(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<StockDefn> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 stock_id = 1;
      public static final int STOCK_ID_FIELD_NUMBER = 1;
      private int stockId_;
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      public boolean hasStockId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 stock_id = 1;</code>
       */
      public int getStockId() {
        return stockId_;
      }

      // required string stock_name = 2;
      public static final int STOCK_NAME_FIELD_NUMBER = 2;
      private java.lang.Object stockName_;
      /**
       * <code>required string stock_name = 2;</code>
       */
      public boolean hasStockName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string stock_name = 2;</code>
       */
      public java.lang.String getStockName() {
        java.lang.Object ref = stockName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stockName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string stock_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStockNameBytes() {
        java.lang.Object ref = stockName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stockName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required int32 stream_id = 3;
      public static final int STREAM_ID_FIELD_NUMBER = 3;
      private int streamId_;
      /**
       * <code>required int32 stream_id = 3;</code>
       */
      public boolean hasStreamId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 stream_id = 3;</code>
       */
      public int getStreamId() {
        return streamId_;
      }

      // repeated int32 pi_ids = 4;
      public static final int PI_IDS_FIELD_NUMBER = 4;
      private java.util.List<java.lang.Integer> piIds_;
      /**
       * <code>repeated int32 pi_ids = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getPiIdsList() {
        return piIds_;
      }
      /**
       * <code>repeated int32 pi_ids = 4;</code>
       */
      public int getPiIdsCount() {
        return piIds_.size();
      }
      /**
       * <code>repeated int32 pi_ids = 4;</code>
       */
      public int getPiIds(int index) {
        return piIds_.get(index);
      }

      private void initFields() {
        stockId_ = 0;
        stockName_ = "";
        streamId_ = 0;
        piIds_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasStockId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStockName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStreamId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, stockId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getStockNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, streamId_);
        }
        for (int i = 0; i < piIds_.size(); i++) {
          output.writeInt32(4, piIds_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, stockId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getStockNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, streamId_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < piIds_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(piIds_.get(i));
          }
          size += dataSize;
          size += 1 * getPiIdsList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static oxberryPis.VisProt.SetupVisualisation.StockDefn parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(oxberryPis.VisProt.SetupVisualisation.StockDefn prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code oxberryPis.SetupVisualisation.StockDefn}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_StockDefn_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_StockDefn_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  oxberryPis.VisProt.SetupVisualisation.StockDefn.class, oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder.class);
        }

        // Construct using oxberryPis.VisProt.SetupVisualisation.StockDefn.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          stockId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          stockName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          streamId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          piIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_StockDefn_descriptor;
        }

        public oxberryPis.VisProt.SetupVisualisation.StockDefn getDefaultInstanceForType() {
          return oxberryPis.VisProt.SetupVisualisation.StockDefn.getDefaultInstance();
        }

        public oxberryPis.VisProt.SetupVisualisation.StockDefn build() {
          oxberryPis.VisProt.SetupVisualisation.StockDefn result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public oxberryPis.VisProt.SetupVisualisation.StockDefn buildPartial() {
          oxberryPis.VisProt.SetupVisualisation.StockDefn result = new oxberryPis.VisProt.SetupVisualisation.StockDefn(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.stockId_ = stockId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.stockName_ = stockName_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.streamId_ = streamId_;
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            piIds_ = java.util.Collections.unmodifiableList(piIds_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.piIds_ = piIds_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof oxberryPis.VisProt.SetupVisualisation.StockDefn) {
            return mergeFrom((oxberryPis.VisProt.SetupVisualisation.StockDefn)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(oxberryPis.VisProt.SetupVisualisation.StockDefn other) {
          if (other == oxberryPis.VisProt.SetupVisualisation.StockDefn.getDefaultInstance()) return this;
          if (other.hasStockId()) {
            setStockId(other.getStockId());
          }
          if (other.hasStockName()) {
            bitField0_ |= 0x00000002;
            stockName_ = other.stockName_;
            onChanged();
          }
          if (other.hasStreamId()) {
            setStreamId(other.getStreamId());
          }
          if (!other.piIds_.isEmpty()) {
            if (piIds_.isEmpty()) {
              piIds_ = other.piIds_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePiIdsIsMutable();
              piIds_.addAll(other.piIds_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasStockId()) {
            
            return false;
          }
          if (!hasStockName()) {
            
            return false;
          }
          if (!hasStreamId()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          oxberryPis.VisProt.SetupVisualisation.StockDefn parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (oxberryPis.VisProt.SetupVisualisation.StockDefn) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 stock_id = 1;
        private int stockId_ ;
        /**
         * <code>required int32 stock_id = 1;</code>
         */
        public boolean hasStockId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 stock_id = 1;</code>
         */
        public int getStockId() {
          return stockId_;
        }
        /**
         * <code>required int32 stock_id = 1;</code>
         */
        public Builder setStockId(int value) {
          bitField0_ |= 0x00000001;
          stockId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 stock_id = 1;</code>
         */
        public Builder clearStockId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          stockId_ = 0;
          onChanged();
          return this;
        }

        // required string stock_name = 2;
        private java.lang.Object stockName_ = "";
        /**
         * <code>required string stock_name = 2;</code>
         */
        public boolean hasStockName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string stock_name = 2;</code>
         */
        public java.lang.String getStockName() {
          java.lang.Object ref = stockName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            stockName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string stock_name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getStockNameBytes() {
          java.lang.Object ref = stockName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            stockName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string stock_name = 2;</code>
         */
        public Builder setStockName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          stockName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string stock_name = 2;</code>
         */
        public Builder clearStockName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          stockName_ = getDefaultInstance().getStockName();
          onChanged();
          return this;
        }
        /**
         * <code>required string stock_name = 2;</code>
         */
        public Builder setStockNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          stockName_ = value;
          onChanged();
          return this;
        }

        // required int32 stream_id = 3;
        private int streamId_ ;
        /**
         * <code>required int32 stream_id = 3;</code>
         */
        public boolean hasStreamId() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int32 stream_id = 3;</code>
         */
        public int getStreamId() {
          return streamId_;
        }
        /**
         * <code>required int32 stream_id = 3;</code>
         */
        public Builder setStreamId(int value) {
          bitField0_ |= 0x00000004;
          streamId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 stream_id = 3;</code>
         */
        public Builder clearStreamId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          streamId_ = 0;
          onChanged();
          return this;
        }

        // repeated int32 pi_ids = 4;
        private java.util.List<java.lang.Integer> piIds_ = java.util.Collections.emptyList();
        private void ensurePiIdsIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            piIds_ = new java.util.ArrayList<java.lang.Integer>(piIds_);
            bitField0_ |= 0x00000008;
           }
        }
        /**
         * <code>repeated int32 pi_ids = 4;</code>
         */
        public java.util.List<java.lang.Integer>
            getPiIdsList() {
          return java.util.Collections.unmodifiableList(piIds_);
        }
        /**
         * <code>repeated int32 pi_ids = 4;</code>
         */
        public int getPiIdsCount() {
          return piIds_.size();
        }
        /**
         * <code>repeated int32 pi_ids = 4;</code>
         */
        public int getPiIds(int index) {
          return piIds_.get(index);
        }
        /**
         * <code>repeated int32 pi_ids = 4;</code>
         */
        public Builder setPiIds(
            int index, int value) {
          ensurePiIdsIsMutable();
          piIds_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 pi_ids = 4;</code>
         */
        public Builder addPiIds(int value) {
          ensurePiIdsIsMutable();
          piIds_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 pi_ids = 4;</code>
         */
        public Builder addAllPiIds(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensurePiIdsIsMutable();
          super.addAll(values, piIds_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 pi_ids = 4;</code>
         */
        public Builder clearPiIds() {
          piIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:oxberryPis.SetupVisualisation.StockDefn)
      }

      static {
        defaultInstance = new StockDefn(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:oxberryPis.SetupVisualisation.StockDefn)
    }

    private int bitField0_;
    // required int32 denomPower = 1;
    public static final int DENOMPOWER_FIELD_NUMBER = 1;
    private int denomPower_;
    /**
     * <code>required int32 denomPower = 1;</code>
     */
    public boolean hasDenomPower() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 denomPower = 1;</code>
     */
    public int getDenomPower() {
      return denomPower_;
    }

    // repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;
    public static final int STOCKS_FIELD_NUMBER = 2;
    private java.util.List<oxberryPis.VisProt.SetupVisualisation.StockDefn> stocks_;
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    public java.util.List<oxberryPis.VisProt.SetupVisualisation.StockDefn> getStocksList() {
      return stocks_;
    }
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    public java.util.List<? extends oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder> 
        getStocksOrBuilderList() {
      return stocks_;
    }
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    public int getStocksCount() {
      return stocks_.size();
    }
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    public oxberryPis.VisProt.SetupVisualisation.StockDefn getStocks(int index) {
      return stocks_.get(index);
    }
    /**
     * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
     */
    public oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder getStocksOrBuilder(
        int index) {
      return stocks_.get(index);
    }

    private void initFields() {
      denomPower_ = 0;
      stocks_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDenomPower()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getStocksCount(); i++) {
        if (!getStocks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, denomPower_);
      }
      for (int i = 0; i < stocks_.size(); i++) {
        output.writeMessage(2, stocks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, denomPower_);
      }
      for (int i = 0; i < stocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, stocks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static oxberryPis.VisProt.SetupVisualisation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static oxberryPis.VisProt.SetupVisualisation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(oxberryPis.VisProt.SetupVisualisation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oxberryPis.SetupVisualisation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements oxberryPis.VisProt.SetupVisualisationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                oxberryPis.VisProt.SetupVisualisation.class, oxberryPis.VisProt.SetupVisualisation.Builder.class);
      }

      // Construct using oxberryPis.VisProt.SetupVisualisation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStocksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        denomPower_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (stocksBuilder_ == null) {
          stocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          stocksBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return oxberryPis.VisProt.internal_static_oxberryPis_SetupVisualisation_descriptor;
      }

      public oxberryPis.VisProt.SetupVisualisation getDefaultInstanceForType() {
        return oxberryPis.VisProt.SetupVisualisation.getDefaultInstance();
      }

      public oxberryPis.VisProt.SetupVisualisation build() {
        oxberryPis.VisProt.SetupVisualisation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public oxberryPis.VisProt.SetupVisualisation buildPartial() {
        oxberryPis.VisProt.SetupVisualisation result = new oxberryPis.VisProt.SetupVisualisation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.denomPower_ = denomPower_;
        if (stocksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            stocks_ = java.util.Collections.unmodifiableList(stocks_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.stocks_ = stocks_;
        } else {
          result.stocks_ = stocksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof oxberryPis.VisProt.SetupVisualisation) {
          return mergeFrom((oxberryPis.VisProt.SetupVisualisation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(oxberryPis.VisProt.SetupVisualisation other) {
        if (other == oxberryPis.VisProt.SetupVisualisation.getDefaultInstance()) return this;
        if (other.hasDenomPower()) {
          setDenomPower(other.getDenomPower());
        }
        if (stocksBuilder_ == null) {
          if (!other.stocks_.isEmpty()) {
            if (stocks_.isEmpty()) {
              stocks_ = other.stocks_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStocksIsMutable();
              stocks_.addAll(other.stocks_);
            }
            onChanged();
          }
        } else {
          if (!other.stocks_.isEmpty()) {
            if (stocksBuilder_.isEmpty()) {
              stocksBuilder_.dispose();
              stocksBuilder_ = null;
              stocks_ = other.stocks_;
              bitField0_ = (bitField0_ & ~0x00000002);
              stocksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStocksFieldBuilder() : null;
            } else {
              stocksBuilder_.addAllMessages(other.stocks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDenomPower()) {
          
          return false;
        }
        for (int i = 0; i < getStocksCount(); i++) {
          if (!getStocks(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        oxberryPis.VisProt.SetupVisualisation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (oxberryPis.VisProt.SetupVisualisation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 denomPower = 1;
      private int denomPower_ ;
      /**
       * <code>required int32 denomPower = 1;</code>
       */
      public boolean hasDenomPower() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 denomPower = 1;</code>
       */
      public int getDenomPower() {
        return denomPower_;
      }
      /**
       * <code>required int32 denomPower = 1;</code>
       */
      public Builder setDenomPower(int value) {
        bitField0_ |= 0x00000001;
        denomPower_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 denomPower = 1;</code>
       */
      public Builder clearDenomPower() {
        bitField0_ = (bitField0_ & ~0x00000001);
        denomPower_ = 0;
        onChanged();
        return this;
      }

      // repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;
      private java.util.List<oxberryPis.VisProt.SetupVisualisation.StockDefn> stocks_ =
        java.util.Collections.emptyList();
      private void ensureStocksIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          stocks_ = new java.util.ArrayList<oxberryPis.VisProt.SetupVisualisation.StockDefn>(stocks_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          oxberryPis.VisProt.SetupVisualisation.StockDefn, oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder, oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder> stocksBuilder_;

      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public java.util.List<oxberryPis.VisProt.SetupVisualisation.StockDefn> getStocksList() {
        if (stocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stocks_);
        } else {
          return stocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public int getStocksCount() {
        if (stocksBuilder_ == null) {
          return stocks_.size();
        } else {
          return stocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public oxberryPis.VisProt.SetupVisualisation.StockDefn getStocks(int index) {
        if (stocksBuilder_ == null) {
          return stocks_.get(index);
        } else {
          return stocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder setStocks(
          int index, oxberryPis.VisProt.SetupVisualisation.StockDefn value) {
        if (stocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStocksIsMutable();
          stocks_.set(index, value);
          onChanged();
        } else {
          stocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder setStocks(
          int index, oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder builderForValue) {
        if (stocksBuilder_ == null) {
          ensureStocksIsMutable();
          stocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          stocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder addStocks(oxberryPis.VisProt.SetupVisualisation.StockDefn value) {
        if (stocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStocksIsMutable();
          stocks_.add(value);
          onChanged();
        } else {
          stocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder addStocks(
          int index, oxberryPis.VisProt.SetupVisualisation.StockDefn value) {
        if (stocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStocksIsMutable();
          stocks_.add(index, value);
          onChanged();
        } else {
          stocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder addStocks(
          oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder builderForValue) {
        if (stocksBuilder_ == null) {
          ensureStocksIsMutable();
          stocks_.add(builderForValue.build());
          onChanged();
        } else {
          stocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder addStocks(
          int index, oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder builderForValue) {
        if (stocksBuilder_ == null) {
          ensureStocksIsMutable();
          stocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          stocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder addAllStocks(
          java.lang.Iterable<? extends oxberryPis.VisProt.SetupVisualisation.StockDefn> values) {
        if (stocksBuilder_ == null) {
          ensureStocksIsMutable();
          super.addAll(values, stocks_);
          onChanged();
        } else {
          stocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder clearStocks() {
        if (stocksBuilder_ == null) {
          stocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          stocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public Builder removeStocks(int index) {
        if (stocksBuilder_ == null) {
          ensureStocksIsMutable();
          stocks_.remove(index);
          onChanged();
        } else {
          stocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder getStocksBuilder(
          int index) {
        return getStocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder getStocksOrBuilder(
          int index) {
        if (stocksBuilder_ == null) {
          return stocks_.get(index);  } else {
          return stocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public java.util.List<? extends oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder> 
           getStocksOrBuilderList() {
        if (stocksBuilder_ != null) {
          return stocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stocks_);
        }
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder addStocksBuilder() {
        return getStocksFieldBuilder().addBuilder(
            oxberryPis.VisProt.SetupVisualisation.StockDefn.getDefaultInstance());
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder addStocksBuilder(
          int index) {
        return getStocksFieldBuilder().addBuilder(
            index, oxberryPis.VisProt.SetupVisualisation.StockDefn.getDefaultInstance());
      }
      /**
       * <code>repeated .oxberryPis.SetupVisualisation.StockDefn stocks = 2;</code>
       */
      public java.util.List<oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder> 
           getStocksBuilderList() {
        return getStocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          oxberryPis.VisProt.SetupVisualisation.StockDefn, oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder, oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder> 
          getStocksFieldBuilder() {
        if (stocksBuilder_ == null) {
          stocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              oxberryPis.VisProt.SetupVisualisation.StockDefn, oxberryPis.VisProt.SetupVisualisation.StockDefn.Builder, oxberryPis.VisProt.SetupVisualisation.StockDefnOrBuilder>(
                  stocks_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          stocks_ = null;
        }
        return stocksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:oxberryPis.SetupVisualisation)
    }

    static {
      defaultInstance = new SetupVisualisation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:oxberryPis.SetupVisualisation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_oxberryPis_StockEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_oxberryPis_StockEvent_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_oxberryPis_SetupVisualisation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_oxberryPis_SetupVisualisation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_oxberryPis_SetupVisualisation_StockDefn_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_oxberryPis_SetupVisualisation_StockDefn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rvisProt.proto\022\noxberryPis\"\230\001\n\nStockEve" +
      "nt\022\020\n\010stock_id\030\001 \002(\005\022\021\n\ttimestamp\030\002 \002(\005\022" +
      "\r\n\005pi_id\030\003 \002(\005\022\025\n\rtop_buy_price\030\004 \001(\005\022\026\n" +
      "\016top_sell_price\030\005 \001(\005\022\023\n\013trade_price\030\006 \001" +
      "(\005\022\022\n\nseq_number\030\007 \002(\005\"\270\001\n\022SetupVisualis" +
      "ation\022\022\n\ndenomPower\030\001 \002(\005\0228\n\006stocks\030\002 \003(" +
      "\0132(.oxberryPis.SetupVisualisation.StockD" +
      "efn\032T\n\tStockDefn\022\020\n\010stock_id\030\001 \002(\005\022\022\n\nst" +
      "ock_name\030\002 \002(\t\022\021\n\tstream_id\030\003 \002(\005\022\016\n\006pi_" +
      "ids\030\004 \003(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_oxberryPis_StockEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_oxberryPis_StockEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_oxberryPis_StockEvent_descriptor,
              new java.lang.String[] { "StockId", "Timestamp", "PiId", "TopBuyPrice", "TopSellPrice", "TradePrice", "SeqNumber", });
          internal_static_oxberryPis_SetupVisualisation_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_oxberryPis_SetupVisualisation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_oxberryPis_SetupVisualisation_descriptor,
              new java.lang.String[] { "DenomPower", "Stocks", });
          internal_static_oxberryPis_SetupVisualisation_StockDefn_descriptor =
            internal_static_oxberryPis_SetupVisualisation_descriptor.getNestedTypes().get(0);
          internal_static_oxberryPis_SetupVisualisation_StockDefn_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_oxberryPis_SetupVisualisation_StockDefn_descriptor,
              new java.lang.String[] { "StockId", "StockName", "StreamId", "PiIds", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
